#!/usr/bin/env bash

################################################################################
# Copyright 2024 Comcast Cable Communications Management, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################

_PWD_PREV=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ "$0" = "${BASH_SOURCE}" ]; then
    echo -e "\nERROR: This script must not be executed but sourced like below"
    echo -e "\n. $0 \nor \nsource $0"
    exit 1
fi

if [ -z "$BASH" -a -z "$ZSH_NAME" ] ;then
    echo Please source this script in bash or zsh shell
    return 1
fi

# check that we are not root!
if [ "$(whoami)" = "root" ]; then
    echo -e "\nERROR: do not use the BSP as root. Exiting..."
    return 1
fi

. $_PWD_PREV/export_manifest_path.sh

MANIFEST_PATH_PRODUCT="$(dirname -- ${MANIFEST_PATH_PRODUCT_LAYER} || echo "$MANIFEST_PATH_MACHINE_CONF_LAYER")"

# check that we are where we think we are!
if [ ! -f "$MANIFEST_PATH_POKY/oe-init-build-env" ]; then
    echo -e "\nUNABLE TO FIND OPENEMBEDDED !"
    return 1
fi

usage () {
    cat <<EOF

Usage: [MACHINE=<MACHINE>] source $BASH_SOURCE [BUILDDIR]
If no MACHINE is set, list all possible machines, and ask user to choose.

EOF
}

# Clean up PATH for local dirs starting with .
export PATH="`echo ${PATH} | sed 's/\(:.\|:\)*:/:/g;s/^.\?://;s/:.\?$//'`"

# Clean PATH of any previous oe-core bitbake or scripts directories
export PATH="$(echo $PATH | sed 's!/[^:]\+/$MANIFEST_PATH_POKY/\(bitbake/bin\|scripts\):!!g')"

# only 1 parameter max, <build> folder, or default to build-$machine
_BUILDDIR=
if [ $# -gt 1 ]; then
    usage
    return 1
elif [ $# -eq 1 ]; then
    _BUILDDIR=$1
    # check if this <build> folder was already configured
    _CONFIGS_FOUND=
    if [ -f ${_BUILDDIR}/conf/local.conf ] && \
        [ -f ${_BUILDDIR}/conf/bblayers.conf ]; then
        _CONFIGS_FOUND="yes"
    fi
fi
# if no MACHINE is set, list common machines and ask user.
# Note: filter out meta-linaro and non-x86 qemu machines from this list to
# avoid confusion (it's still possible to select any valid machine manually).
while [ -z "$MACHINE" ] && [ -z "$_CONFIGS_FOUND" ]; do

    _options=$(\ls -1 ${MANIFEST_PATH_PRODUCT}*{,/*}/conf/machine/*.conf 2>/dev/null | grep -v '\(^meta-linaro\|^meta-intel\|/qemumips\|/qemuppc\)')
    _options_count=`echo ${_options} | wc -w`
    PS3="Please enter your choice of machine [1..${_options_count}]: "
    
    select opt in `echo $_options`
    do
        if [ -z "$opt" ]; then
            echo "Invalid choice"
        else
	    MACHINE=$(echo $opt | sed 's|.*/\(.*\)\.conf|\1|')
            break;
        fi
    done
    unset PS3 _options_count _options
done

# Setting CPC_CUSTOM_STAMP in auto.conf
if [ -f "generic/yocto-hooks/$MACHINE/setup-datetime.sh" ]; then
    ./generic/yocto-hooks/$MACHINE/setup-datetime.sh
fi

# at this point, MACHINE is set, either from env, or explicitely
# BUILDIR is either set from command line, or needs to be set to build-$MACHINE
if [ -z "$_BUILDDIR" ]; then
    _BUILDDIR=build-$MACHINE
    # check if this build-$MACHINE folder was already configured
    if [ -f ${_BUILDDIR}/conf/local.conf ] && \
        [ -f ${_BUILDDIR}/conf/bblayers.conf ]
    then
        _CONFIGS_FOUND="yes"
    fi
fi

mkdir -p "$_BUILDDIR/conf"

if [ ! -d "$_BUILDDIR/conf" ]; then
    echo >&2 "Error: The builddir/conf ($_BUILDDIR/conf) does not exist!"
    exit 1
fi

if [ -f "${_PWD_PREV}/../manifest_vars.conf" ];
then
        echo "MW_LAYER_BUILD_TYPE = \"${MW_LAYER_BUILD_TYPE}\"" >> ${_PWD_PREV}/../manifest_vars.conf
        mv ${_PWD_PREV}/../manifest_vars.conf ${_BUILDDIR}/conf/manifest_vars.conf
fi

# Warning: Sourcing the oe-init-build-env script changes the current directory.
TEMPLATECONF=$MANIFEST_PATH_BBLAYERS_TEMPLATE/conf/template/ source $MANIFEST_PATH_POKY/oe-init-build-env ${_BUILDDIR}

if [ "$_CONFIGS_FOUND" ]; then
    echo -e "\nConfig files already exist in folder ${_BUILDDIR}/conf/, they were not modified."
    unset -f usage
    unset _BUILDDIR _CONFIGS_FOUND _PWD_PREV MACHINE
    return 0
fi

# Product-layer custom local.conf override (vdevice layers ONLY)
# For product layers containing 'vdevice' in the path, use custom local.conf from the product layer
# instead of the default TEMPLATECONF template. Other product layers continue to use default behavior.
# This allows vdevice-specific configurations to be maintained in the product layer itself.

if [[ "${MANIFEST_PATH_PRODUCT_LAYER}" == *"vdevice"* ]] && [ -f "${MANIFEST_PATH_PRODUCT_LAYER}/conf/template/local.conf.sample" ]; then
    cp -f "${MANIFEST_PATH_PRODUCT_LAYER}/conf/template/local.conf.sample" conf/local.conf
    echo -e "\nUsing product-layer local.conf from: ${MANIFEST_PATH_PRODUCT_LAYER}/conf/template/local.conf.sample"
fi

# Determine DISTRO_CODENAME from the bitbake version
# Warning: The RDK has historically combined bitbake 1.28 (ie the version of
# bitbake released with OE 2.0) with OE 1.6. We need to account for that here,
# ie bitbake version 1.28 needs to map to "daisy", not "jethro".

case "$(sed -n 's/^__version__ = "\(.*\)"/\1/p' $MANIFEST_PATH_POKY/bitbake/bin/bitbake)"
in
    2.0.*) _DISTRO_CODENAME="kirkstone" ;;
    2.2.*) _DISTRO_CODENAME="kirkstone" ;;
    1.46.*) _DISTRO_CODENAME="dunfell" ;;
    1.37.*|1.38.*) _DISTRO_CODENAME="sumo" ;;
    1.35.*|1.36.*) _DISTRO_CODENAME="rocko" ;;
    1.34.*) _DISTRO_CODENAME="pyro" ;;
    1.32.*) _DISTRO_CODENAME="morty" ;;
    1.30.*) _DISTRO_CODENAME="krogoth" ;;
    *)      _DISTRO_CODENAME="daisy" ;;
esac

sed -e "s/##DISTRO_CODENAME##/$_DISTRO_CODENAME/g" \
    -i conf/local.conf

sed -e "s/##MW_LAYER_BUILD_TYPE##/${MW_LAYER_BUILD_TYPE}/g" -i conf/local.conf

#Added to install the debug tool packages
echo 'RDK_TOOLS_PACKAGES = ""' >> conf/local.conf

# Check the machine type specified
_VALID_MACHINES=$(\ls -1 ${MANIFEST_PATH_PRODUCT}*{,/*}/conf/machine/${MACHINE}.conf 2>/dev/null | wc -l)
if [ "$_VALID_MACHINES" -eq 0 ]; then
    echo -e "\n##\n## WARNING: No machine configs found for '$MACHINE' !"
    echo -e "##\n## That looks very suspicious, you should check your configuration"
    echo -e "##\n## Possible alternatives might be:\n##"
    ( cd ${_PWD_PREV} && \ls -1 ${MANIFEST_PATH_PRODUCT}*{,/*}/conf/machine/*.conf 2>/dev/null | sed 's|.*/\(.*\)\.conf|##   \1|' | sort | uniq )
    echo -e "##"
elif [ "$_VALID_MACHINES" -gt 1 ]; then
    echo -e "\n##\n## WARNING: Multiple possible machine configs found for '$MACHINE' !\n##"
    ( cd ${_PWD_PREV} && \ls -1 ${MANIFEST_PATH_PRODUCT}*{,/*}/conf/machine/${MACHINE}.conf 2>/dev/null | sed 's|^|##   |' )
    echo -e "##\n## That looks very suspicious, you should check your source tree\n##"
fi

# Change settings according environment
sed -e "s/##MACHINE##/$MACHINE/g" \
    -i conf/local.conf

# Added support for building from source
if [ -z $LAYER_SRC_MODE ]; then
    LAYER_SRC_MODE="0"
fi
echo "# Added support for building from source" >> conf/local.conf
echo "# and disable/enable ipk mode" >> conf/local.conf
echo "LAYER_SRC_MODE = \"$LAYER_SRC_MODE\"" >> conf/local.conf

# Added support for debugfs
if [ -z $DEBUGFS ]; then
    DEBUGFS="0"
fi
echo "# Added support for generating debugfs " >> conf/local.conf
echo "IMAGE_GEN_DEBUGFS = \"$DEBUGFS\"" >> conf/local.conf

# Standardize the TARGET_VENDOR variable
if [ -z "$TARGET_VENDOR" ]; then
    TARGET_VENDOR="-rdk"
fi
echo "# Standardize the TARGET_VENDOR variable" >> conf/local.conf
echo "# The TARGET_VENDOR variable is used to generate the folder structure for toolchain components." >> conf/local.conf
echo "TARGET_VENDOR = \"$TARGET_VENDOR\"" >> conf/local.conf


if [ -f ${_PWD_PREV}/../auto.conf ]; then
    ln -s ${_PWD_PREV}/../auto.conf conf/auto.conf
fi

cat <<EOF

Configuration files have been created for the following configuration:

 DISTRO: ${_RDK_FLAVOR}
 MACHINE: $MACHINE

EOF

(
set +e
# Hook for multiconfig build, where we create multiconfig directory under build conf directory and
# copy mc conf files
mul_hooks=$(ls -1 ../*{,/*/*}/conf/machine/post-builddir-$MACHINE.sh 2>/dev/null)
if [ -f "$mul_hooks" ]; then
        echo "running script $mul_hooks"
        source $mul_hooks $MACHINE
fi
)

# Since this script is sourced, be careful not to pollute caller's environment with temp variables
unset -f usage
unset _BUILDDIR _CONFIGS_FOUND _PWD_PREV _VALID_MACHINES _NCPU _BSP MACHINE _LAYERS _MACH_CONF _BSP_LAYER_REQUIRED _DISTRO_CODENAME
